config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root 'welcome#index'

  resources :topics do
    resources :posts do
      member do
        post :create_comment
        delete :destroy_comment
      end
    end
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, :as => :commentable
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments, :as => :commentable
  

  NICK_OPTIONS = [
    "His winning smile",
    "His spelling and grammar",
    "His taste in cars",
    "His humble attitude",
    "His shirts",
    "Other"
  ]
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :nick_thing) }
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def new
    @topic = Topic.find params[:topic_id]
    @post = Post.new
  end

  def show
    @topic = Topic.find params[:topic_id]
    @post = Post.find params[:id]
    @comment = Comment.new
    @comments = @post.comments
  end

  def create
    @topic = Topic.find params[:topic_id]
    @post = @topic.posts.create post_params
    @post.user = current_user
    @post.save
    redirect_to topic_path(@topic)
  end

  def edit
    @topic = Topic.find params[:topic_id]
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    @topic = Topic.find params[:topic_id]
    @post.update_attributes post_params
    redirect_to topic_path(@topic)
  end

  def destroy
    @topic = Topic.find params[:topic_id]
    @post = Post.find params[:id]
    @post.destroy
    redirect_to @topic
  end

  def create_comment
    @topic = Topic.find params[:topic_id]
    @post = Post.find params[:id]
    @comment = @post.comments.create comment_params
    @comment.user = current_user
    @comment.save
    redirect_to topic_post_path(@topic, @post)
  end

  def destroy_comment
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to topic_post_path(@comment.commentable.topic, @comment.commentable)
  end

  def comment_params
    params.require(:comment).permit(
        :title,
        :content,
    )
  end

  def post_params
    params.require(:post).permit(
        :title,
        :content,
        user_ids: []

    )
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	def index
		@topics = Topic.all
	end
	
	def new
		@topic = Topic.new
	end	

	def create
		@topic = Topic.create topic_params
		@topic.user = current_user
		@topic.save
		redirect_to topics_path
	end	

	def show
		@topic = Topic.find params[:id]
		@posts = @topic.posts
	end

	def edit
		@topic = Topic.find params[:id]
	end	

	def update
		@topic = Topic.find params[:id]
		@topic.update_attributes topic_params
		redirect_to topics_path
	end	

	def destroy
    @topic = Topic.find params[:id]
    @topic.delete
    redirect_to topics_path
  end

private
	def topic_params
		params.require(:topic).permit(
			:title,
			:initial_post
			)
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %p.text-center Nick Bucciarelli Forum

app/views/layouts/_navbar.html.haml
/ Static navbar
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Nick Bucciarelli Forum
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Topics
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Topic # 1
            %li
              %a{:href => "#"} Topic # 2
            %li
              %a{:href => "#"} Topic # 3
      %ul.nav.navbar-nav.navbar-right
        %li.active
          %a{:href => "/users/sign_up"}
            Register
            %span.sr-only (current)
        %li
          %a{:href => "/users/sign_in"} Login
        %li
          = link_to "Log Out", destroy_user_session_path, method: :delete
    / /.nav-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Nick Bucciarelli Forum
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container
      .row
        .col-md-12.text-center
          %p.notice= notice
          %p.alert= alert
    = yield

    = render 'layouts/footer'

app/views/posts/_form.html.haml
.container
  .row
    .col-md-12.text-center
      = form_for [@topic, @post] do |f|
        = f.label :title
        = f.text_field :title
        %br
        = f.label :content
        = f.text_area :content
        %br
          = f.submit

app/views/posts/edit.html.haml
%h1

= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  = post.title
  %br
  = post.content
  %br
  = link_to "Edit", edit_post_path(post)
  = link_to "Delete", post_path(post), method: :delete

app/views/posts/new.html.haml
.container
  .row
    .col-md-12.text-center
      %h2 New Post

= render 'form'

app/views/posts/show.html.haml
.container
  .row
    .col-md-12.text-center
      %h2
        = @post.title
      %br
      %br
        = @post.content
      %br
        = @post.user.email
      %br
        = link_to "Edit", edit_topic_post_path(@topic, @post)
        |
        = link_to "Delete", topic_post_path(@topic, @post), method: :delete
%br
.container-fluid.text-center
  .row
    .col-md-12.text-center
      Add Comment to Post: 
      = form_for @comment, url: create_comment_topic_post_path(@topic, @post) do |f|
        = f.label :title
        = f.text_field :title
        %br
        = f.label :content
        = f.text_area :content
        %br
        = f.submit
%br
.container-fluid.text-center
  .row      
    Comment List
    %br
    - @comments.each do |comment|
      .col-md-12.text-center
        %br
        .list-group-item.text-left
          %br
          %strong
            = comment.title
          %br
          = comment.content
          %br
          = comment.created_at.strftime("commented at %I:%M%p")
          %br
          = comment.user.email
          %br
          = link_to "Delete", destroy_comment_topic_post_path(@post, comment), method: :delete

app/views/topics/_form.html.haml
.container
  .row
    .col-md-12.text-center
      = form_for @topic do |f|
        .form-group
          = f.label :title
          = f.text_field :title
        %br
        .form-group
          = f.label :initial_post
          = f.text_area :initial_post
        %br
        %br
        = f.submit
        %br
        = link_to "Home", root_path

app/views/topics/edit.html.haml
.container
  .row
    .col-md-12.text-center
      %h1 Edit Topic

= render 'form'

app/views/topics/index.html.haml
.container
  .row
    .col-md-12.jumbotron
      %h1 Topics
.container
  .row
    - @topics.each do |topic|
      .col-md-4
        .list-group-item
          %h3
            = link_to topic.title, topic_path(topic)
          %br
          = topic.initial_post
          %br
          = topic.created_at.strftime("created at %I:%M%p")
          %br
          = topic.user.email
          %br
.container
  .row
    .col-md-12.text-center
      = link_to "Home", root_path
      |
      = link_to "Add Topic", new_topic_path

app/views/topics/new.html.haml
.container
  .row
    .col-md-12.text-center
      %h1 Add A New Topic About Nick

= render 'form'

app/views/topics/show.html.haml
.container
  .row
    .col-md-12.text-center
      %h2
        = @topic.title
      %br
      %br
      = @topic.initial_post
      %br
      = @topic.user.email
      %br
      = @topic.created_at.strftime("posted at %I:%M%p")
      %br
      = link_to "Edit", edit_topic_path(@topic, @post)
      |
      = link_to "Delete", topic_path(@topic), method: :delete
      |
      = link_to "Home", root_path
%br
.container-fluid.text-center
  .row      
    = link_to "Join the Conversation! Add a Post", new_topic_post_path(@topic)
    %br
    - @posts.each do |post|
      .col-md-12.text-center
        %br
        .list-group-item.text-left
          %strong 
            = link_to post.title, topic_post_path(@topic, post)
          %br
          = post.content
          %br
          = post.created_at.strftime("posted at %I:%M%p")
          %br
          = post.user.email
          %br
          = link_to "Edit", edit_topic_post_path(@topic, post)
          |
          = link_to "Delete", topic_post_path(@topic, post), method: :delete
          |
          = link_to "Add Comment", topic_post_path(@topic, post)
          %br

app/views/users/index.html.haml
= link_to "User Sign up", new_user_registration_path
= link_to "Log Out", destroy_user_session_path, method: :delete

app/views/users/show.html.haml
%h3User
= @user.name if @user.name
= @user.email if @user.email 

app/views/welcome/index.html.haml
.container
  .row
    .jumbotron
      %h1 Nick Nation
      %p THE BEST Nick Bucciarelli Fan Forum
      %p
        %a.btn.btn-danger.btn-lg{:href => "/topics", :role => "button"} Visit Forum
.container
  .row
    .col-md-12.text-center
      = link_to 'Users:', users_path
      = User.count
      registered
.container
  .row
    .col-md-12.text-center
      #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
        / Indicators
        %ol.carousel-indicators
          %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
          %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
          %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
        / Wrapper for slides
        .carousel-inner{:role => "listbox"}
          .item.active
            %img{:alt => "...", :src => "https://scontent-b-atl.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/40939_554119405050_1337143_n.jpg?oh=137f883f1d8acd91f0c8878bbdd57e3c&oe=556E8E20"}
              .carousel-caption
                %h3 Discuss your favorite Nick moments
          .item
            %img{:alt => "...", :src => "https://scontent-b-atl.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/1928244_518610929320_6783226_n.jpg?oh=18b97db5f3621c9a5e61c21e51cead68&oe=55237494"}
              .carousel-caption
                %h3 Swap your favorite leg day routines
          \...
        / Controls
        %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
          %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
          %span.sr-only Previous
        %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
          %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
          %span.sr-only Next